### ISSUE TITLE
Backend script condition never true

### ISSUE THREAD

**Issue by pezlin** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#4]
I am trying to run the script but can see that only the first three sensors are created from the "first" script. The backend script is successfully triggered from the first script but it never does anything due to that the condition is always false. It looks a bit strange when checking the yaml (both condition and sequence get blue in the color coded UI) but I can't figure out what to do

**Comment by mekaneck** [comment]
[Line 137](https://github.com/mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery/blob/9a4f2ba547782c5fb3a43f6d4673de7067430654/teslamate_mqtt_device_creation_script.yaml#L137) is the first line that executes the backend script, and there should be no condition or IF statement that controls that line or anything beyond it. Every time `teslamate_create` is executed, line 137 - 832 should always be executed unless the script aborts due to some sort of error. Can you clarify which condition is preventing the execution of these lines?

I'm also interested to know which code editor you're using which color codes the YAML.

**Comment by mekaneck** [comment]
I believe I found the issue you described; I misunderstood your comment. You were correct there was a condition in the backend script preventing execution. The purpose of the condition is to prevent accidental execution of the backend script from the UI, however I implemented the logic incorrectly. 

Please let me know if the update resolves your issue.

**Comment by pezlin** [comment]
Seems to be working now. Thanks!
