### ISSUE TITLE
Location entity not working

### ISSUE THREAD

**Issue by pezlin** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#8]
The Location entity (home/not_home) is not working for me most of the times. I have an automation setup according to the guide but still it is quit common that the location is displaying as not_home when the car is home. Any suggestions on how to troubleshoot this?

**Comment by mekaneck** [comment]
The entity should be based on the geofence entity. So first step would be to verify whether the geofence entity is showing 'home' when the car is home. And note that the geofence entity is set based upon what geofence locations you have configured in Teslamate. When the car is not within any geofence the sensor status will be blank, otherwise the sensor will reflect which geofence your car is located within.

**Comment by pezlin** [comment]
Hm, I did setup the geofence after the entity was created. Could that perhaps have an impact? The Geofence is showing correctly but it does not (always) update the Location entity.

**Comment by pezlin** [comment]
This is till not working. The geofence entity is updating as expected and the GPS attributes of the Location entity is updated but the state of the Location entity is showing incorrectly most of the times.

**Comment by mekaneck** [comment]
I'm slowly making some progress on this. I'm having the same issue. What I believe is happening is that the device_tracker state is only evaluated when there is an MQTT update made to the `teslamate/cars/x/latitude` topic. Often, the geofence entity does not update until slightly after the final change of latitude, and therefore the device_tracker is never forced to update when the geofence is `home`. 

I'm looking at different ways to rewrite the value_template or to force an update of the device_tracker entity.

**Comment by mekaneck** [comment]
I tied the state to the geofence entity, so now the sensor state is immediately updated when teslamate publishes an update to the .../geofence topic.

I will note I did discover that the `device_tracker.<tesla_name>_location` sensor will only have its GPS coordinates updated when there is a latitude change. Longitude changes will not trigger an update. So if you somehow manage to travel in your car along a line perfectly parallel to a line of latitude, you will not see any longitude updates. The only way to correct this is to create some automations and force an update but I feel the difficulty of the solution is not worth it since this is so unlikely to ever be an issue.
